// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Pubquizish.Game.Infrastructure.EntityFramework;

namespace api.Migrations.GameDb
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20210913161035_Added creator to new game")]
    partial class Addedcreatortonewgame
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("Pubquizish.Game.NewGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("_code")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Code");

                    b.Property<Guid>("_creator")
                        .HasColumnType("TEXT")
                        .HasColumnName("Creator");

                    b.Property<string>("_name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("NewGames");
                });
#pragma warning restore 612, 618
        }
    }
}
