// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pubquizish.Game.Infrastructure.EntityFramework;

#nullable disable

namespace api.Migrations.GameDb
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20220801102519_AddPlayableGame")]
    partial class AddPlayableGame
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("Pubquizish.Game.Domain.NewGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("_code")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Code");

                    b.Property<DateTime>("_createdOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedOn");

                    b.Property<Guid>("_creatorId")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatorId");

                    b.Property<string>("_name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("NewGames");
                });

            modelBuilder.Entity("Pubquizish.Game.Domain.PlayableGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("_code")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Code");

                    b.Property<DateTime>("_createdOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedOn");

                    b.Property<Guid>("_creatorId")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatorId");

                    b.Property<string>("_name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("PlayableGame");
                });
#pragma warning restore 612, 618
        }
    }
}
